name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/%D7%A0%D7%95%D7%A2%D7%94_%D7%A7%D7%99%D7%A8%D7%9C_-_%D7%A6%D7%99%D7%9C%D7%95%D7%9D_%D7%93%D7%A0%D7%99%D7%90%D7%9C_%D7%90%D7%9C%D7%A1%D7%98%D7%A8_%28cropped%29.jpg'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Download file
        run: |
          # Create downloads directory if it doesn't exist
          mkdir -p downloads
          # Download the file using curl
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/downloaded_file"
        
      - name: Track large file with Git LFS
        run: git lfs track "downloads/downloaded_file"

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .gitattributes downloads/downloaded_file
          git commit -m "Add downloaded file to Git LFS"
          git push
