name: Download and Upload Large File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install aria2 for efficient downloading
        run: sudo apt-get install -y aria2

      - name: Download file
        run: |
          aria2c -d /tmp -o largefile.ext "https://filehippo.com/download-launch/fifa-12/windows/?dt=internalDownload&token=RAvvK7CNFamPi1fsBO1U9FirlBjpIWtX2dL150yTFt0"
          echo "Downloaded file:"
          find /tmp -name "largefile.ext"
          if [ ! -f /tmp/largefile.ext ]; then
            echo "Error: File /tmp/largefile.ext not found!"
            exit 1
          else
            echo "File downloaded successfully to /tmp/largefile.ext"
          fi

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Remove file extension
        run: mv /tmp/largefile.ext /tmp/largefile

      - name: Upload file to repository using Git LFS
        run: |
          mkdir -p downloads
          mv /tmp/largefile downloads/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git lfs track "downloads/largefile"
          git add .gitattributes
          git add downloads/largefile
          git commit -m 'Add downloaded large file without extension'
          git push
