name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://www.google.com/imgres?q=%D7%AA%D7%9E%D7%95%D7%A0%D7%94%20%D7%A9%D7%9C%20%D7%A0%D7%95%D7%A2%D7%94%20%D7%A7%D7%99%D7%A8%D7%9C&imgurl=https%3A%2F%2Fsuperpharmstorage.blob.core.windows.net%2Fhybris%2Fbrands%2Fnoa-kirel%2Fheader-mobile.jpg&imgrefurl=https%3A%2F%2Fshop.super-pharm.co.il%2Fnoa-kirel&docid=TtZGj0lBiSPJOM&tbnid=N9DtZjXfOGTWDM&vet=12ahUKEwiDhb-8zNqLAxVL0gIHHYJvLFYQM3oECH0QAA..i&w=800&h=600&hcb=2&ved=2ahUKEwiDhb-8zNqLAxVL0gIHHYJvLFYQM3oECH0QAA'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Download file
        run: |
          # Create downloads directory if it doesn't exist
          mkdir -p downloads
          # Download the file using curl
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/downloaded_file"
        
      - name: Track large file with Git LFS
        run: git lfs track "downloads/downloaded_file"

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .gitattributes downloads/downloaded_file
          git commit -m "Add downloaded file to Git LFS"
          git push
