name: Download and Upload File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://mirrors.dotsrc.org/kiwix/zim/wikipedia/wikipedia_he_all_mini_2024-06.zim'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          # Create downloads directory if it doesn't exist
          mkdir -p downloads
          # Download the file using curl
          curl -L "${{ github.event.inputs.file_url }}" -o "downloads/downloaded_file"
        
      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloads/downloaded_file
          git commit -m "Add downloaded file"
          git push
