name: Download YouTube Video (via Pytube)

on:
  workflow_dispatch:

jobs:
  download-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytube requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create downloads directory
        run: mkdir -p downloads

      - name: Create download script
        run: |
          cat > download_video.py << 'EOL'
          from pytube import YouTube
          import sys
          from time import sleep
          
          def download_video(url, output_path):
              for attempt in range(3):
                  try:
                      print(f"Attempt {attempt + 1} to download video...")
                      yt = YouTube(
                          url,
                          use_oauth=False,
                          allow_oauth_cache=False
                      )
                      
                      # בחר את האיכות הטובה ביותר בפורמט MP4
                      video = yt.streams.filter(
                          progressive=True,
                          file_extension='mp4'
                      ).order_by('resolution').desc().first()
                      
                      if not video:
                          print("No suitable video stream found")
                          continue
                      
                      print(f"Downloading: {yt.title}")
                      video.download(output_path=output_path, filename='video.mp4')
                      print("Download completed successfully!")
                      return True
                      
                  except Exception as e:
                      print(f"Error occurred: {str(e)}")
                      if attempt < 2:
                          print("Waiting 30 seconds before retry...")
                          sleep(30)
                      continue
              
              return False
          
          if __name__ == "__main__":
              video_url = "https://www.youtube.com/watch?v=i0tFsOAMmBs"
              if not download_video(video_url, "downloads"):
                  sys.exit(1)
          EOL

      - name: Download video
        run: python download_video.py

      - name: Verify download
        run: |
          if [ ! -f downloads/video.mp4 ]; then
            echo "Video download failed or file not found"
            exit 1
          fi
          echo "Video downloaded successfully"
          ls -lh downloads/

      - name: Setup Git LFS file tracking
        run: |
          git lfs track "downloads/video.mp4"
          git add .gitattributes

      - name: Commit and push video
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "downloads/video.mp4"
          git commit -m "Add downloaded video"
          git push
