name: Download YouTube Video (via Invidious)

on:
  workflow_dispatch:

jobs:
  download-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl ffmpeg jq wget

      - name: Create downloads directory
        run: mkdir -p downloads

      - name: Download video
        run: |
          # הגדר את מזהה הסרטון
          VIDEO_ID="i0tFsOAMmBs"
          OUTPUT_NAME="video"
          
          # רשימת שרתי Invidious זמינים
          INVIDIOUS_INSTANCES=(
            "https://invidious.snopyta.org"
            "https://yewtu.be"
            "https://invidious.kavin.rocks"
            "https://vid.puffyan.us"
          )
          
          download_successful=false
          
          for instance in "${INVIDIOUS_INSTANCES[@]}"; do
            echo "Trying instance: $instance"
            
            # קבל מידע על הסרטון מה-API
            video_info=$(curl -s "$instance/api/v1/videos/$VIDEO_ID")
            
            if [ $? -eq 0 ] && [ ! -z "$video_info" ]; then
              # נסה למצוא את הURL של הסרטון באיכות הטובה ביותר
              video_url=$(echo "$video_info" | jq -r '.formatStreams[] | select(.container=="mp4") | .url' | head -n 1)
              
              if [ ! -z "$video_url" ]; then
                echo "Found video URL, attempting download..."
                
                # נסה להוריד את הסרטון
                if wget -O "downloads/${OUTPUT_NAME}.mp4" "$video_url"; then
                  download_successful=true
                  echo "Download successful!"
                  break
                fi
              fi
            fi
            
            echo "Failed with this instance, trying next..."
            sleep 5
          done
          
          if [ "$download_successful" = false ]; then
            echo "Failed to download video from all instances"
            exit 1
          fi

      - name: Verify download
        run: |
          if [ ! -f downloads/video.mp4 ]; then
            echo "Video download failed or file not found"
            exit 1
          fi
          echo "Video downloaded successfully"
          ls -lh downloads/

      - name: Setup Git LFS file tracking
        run: |
          git lfs track "downloads/video.mp4"
          git add .gitattributes

      - name: Commit and push video
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "downloads/video.mp4"
          git commit -m "Add downloaded video"
          git push
