name: Download YouTube Video (Static Configuration)

on:
  workflow_dispatch:    # ניתן להפעיל ידנית בלי צורך בהזנת פרמטרים

jobs:
  download-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          yt-dlp --version

      - name: Create downloads directory
        run: mkdir -p downloads

      - name: Download YouTube video
        run: |
          # הגדר את כתובת הסרטון ושם הקובץ כאן
          VIDEO_URL="https://www.youtube.com/watch?v=i0tFsOAMmBs"
          OUTPUT_NAME="my_video"
          
          for i in {1..3}; do
            echo "Attempt $i to download video..."
            yt-dlp \
              --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' \
              --merge-output-format mp4 \
              --output "downloads/${OUTPUT_NAME}.%(ext)s" \
              --no-cookies \
              --no-cache-dir \
              --no-check-certificates \
              --force-ipv4 \
              --ignore-errors \
              --no-warnings \
              "${VIDEO_URL}" && break || {
                if [[ $i == 3 ]]; then
                  echo "Failed all download attempts"
                  exit 1
                fi
                echo "Download failed, waiting 10 seconds before retry..."
                sleep 10
              }
          done

      - name: Verify download
        run: |
          OUTPUT_NAME="my_video"  # חייב להיות זהה לשם שהוגדר בשלב הקודם
          if [ ! -f downloads/${OUTPUT_NAME}.mp4 ]; then
            echo "Video download failed or file not found"
            exit 1
          fi
          echo "Video downloaded successfully"
          ls -lh downloads/

      - name: Setup Git LFS file tracking
        run: |
          OUTPUT_NAME="my_video"  # חייב להיות זהה לשם שהוגדר בשלבים הקודמים
          git lfs track "downloads/${OUTPUT_NAME}.mp4"
          git add .gitattributes

      - name: Commit and push video
        run: |
          OUTPUT_NAME="my_video"  # חייב להיות זהה לשם שהוגדר בשלבים הקודמים
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "downloads/${OUTPUT_NAME}.mp4"
          git commit -m "Add downloaded YouTube video: ${OUTPUT_NAME}"
          git push
