name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
        default: 'https://www.youtube.com/watch?v=example'

jobs:
  download-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Install yt-dlp
        run: |
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Create downloads directory
        run: mkdir -p downloads

      - name: Download YouTube video
        run: |
          cd downloads
          yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' \
                 --merge-output-format mp4 \
                 --output "video" \
                 "${{ github.event.inputs.video_url }}"

      - name: Track video with Git LFS
        run: git lfs track "downloads/video"

      - name: Commit and push video
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .gitattributes downloads/video
          git commit -m "Add downloaded YouTube video to Git LFS"
          git push